// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_SCENENODETYPES_H_
#define FLATBUFFERS_GENERATED_SCENENODETYPES_H_

#include "flatbuffers/flatbuffers.h"

enum SceneNodeType {
  SceneNodeType_SceneRoot = 0,
  SceneNodeType_Actor = 1,
  SceneNodeType_Frustum = 2,
  SceneNodeType_Camera = 3,
  SceneNodeType_Light = 4,
  SceneNodeType_Max = 5,
  SceneNodeType_MIN = SceneNodeType_SceneRoot,
  SceneNodeType_MAX = SceneNodeType_Max
};

inline const char **EnumNamesSceneNodeType() {
  static const char *names[] = { "SceneRoot", "Actor", "Frustum", "Camera", "Light", "Max", nullptr };
  return names;
}

inline const char *EnumNameSceneNodeType(SceneNodeType e) { return EnumNamesSceneNodeType()[static_cast<int>(e)]; }

#endif  // FLATBUFFERS_GENERATED_SCENENODETYPES_H_
